language: python
python:
  - "3.5-dev" # 3.5 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
  - pip install coveralls
  - pip install coverage
script:
  - nosetests --with-coverage # or py.test for Python versions 3.5 and below
after_success:
  - coverall
