language: python
python:
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
  - pip install coveralls

script:
  - pytest # or py.test for Python versions 3.5 and below
after-success:
  - coverall
